/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as NewProductsRouteImport } from './routes/new-products'
import { Route as LatestOffersRouteImport } from './routes/latest-offers'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CancelOrderRouteImport } from './routes/cancel-order'
import { Route as BestSellersRouteImport } from './routes/best-sellers'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const NewProductsRoute = NewProductsRouteImport.update({
  id: '/new-products',
  path: '/new-products',
  getParentRoute: () => rootRouteImport,
} as any)
const LatestOffersRoute = LatestOffersRouteImport.update({
  id: '/latest-offers',
  path: '/latest-offers',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CancelOrderRoute = CancelOrderRouteImport.update({
  id: '/cancel-order',
  path: '/cancel-order',
  getParentRoute: () => rootRouteImport,
} as any)
const BestSellersRoute = BestSellersRouteImport.update({
  id: '/best-sellers',
  path: '/best-sellers',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/best-sellers': typeof BestSellersRoute
  '/cancel-order': typeof CancelOrderRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact-us': typeof ContactUsRoute
  '/favorites': typeof FavoritesRoute
  '/latest-offers': typeof LatestOffersRoute
  '/new-products': typeof NewProductsRoute
  '/order-success': typeof OrderSuccessRoute
  '/orders': typeof OrdersRoute
  '/payment': typeof PaymentRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track': typeof TrackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/best-sellers': typeof BestSellersRoute
  '/cancel-order': typeof CancelOrderRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact-us': typeof ContactUsRoute
  '/favorites': typeof FavoritesRoute
  '/latest-offers': typeof LatestOffersRoute
  '/new-products': typeof NewProductsRoute
  '/order-success': typeof OrderSuccessRoute
  '/orders': typeof OrdersRoute
  '/payment': typeof PaymentRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track': typeof TrackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/best-sellers': typeof BestSellersRoute
  '/cancel-order': typeof CancelOrderRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact-us': typeof ContactUsRoute
  '/favorites': typeof FavoritesRoute
  '/latest-offers': typeof LatestOffersRoute
  '/new-products': typeof NewProductsRoute
  '/order-success': typeof OrderSuccessRoute
  '/orders': typeof OrdersRoute
  '/payment': typeof PaymentRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track': typeof TrackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/best-sellers'
    | '/cancel-order'
    | '/cart'
    | '/checkout'
    | '/contact-us'
    | '/favorites'
    | '/latest-offers'
    | '/new-products'
    | '/order-success'
    | '/orders'
    | '/payment'
    | '/shop'
    | '/sitemap.xml'
    | '/track'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/best-sellers'
    | '/cancel-order'
    | '/cart'
    | '/checkout'
    | '/contact-us'
    | '/favorites'
    | '/latest-offers'
    | '/new-products'
    | '/order-success'
    | '/orders'
    | '/payment'
    | '/shop'
    | '/sitemap.xml'
    | '/track'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/best-sellers'
    | '/cancel-order'
    | '/cart'
    | '/checkout'
    | '/contact-us'
    | '/favorites'
    | '/latest-offers'
    | '/new-products'
    | '/order-success'
    | '/orders'
    | '/payment'
    | '/shop'
    | '/sitemap.xml'
    | '/track'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  BestSellersRoute: typeof BestSellersRoute
  CancelOrderRoute: typeof CancelOrderRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactUsRoute: typeof ContactUsRoute
  FavoritesRoute: typeof FavoritesRoute
  LatestOffersRoute: typeof LatestOffersRoute
  NewProductsRoute: typeof NewProductsRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  OrdersRoute: typeof OrdersRoute
  PaymentRoute: typeof PaymentRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrackRoute: typeof TrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-products': {
      id: '/new-products'
      path: '/new-products'
      fullPath: '/new-products'
      preLoaderRoute: typeof NewProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latest-offers': {
      id: '/latest-offers'
      path: '/latest-offers'
      fullPath: '/latest-offers'
      preLoaderRoute: typeof LatestOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancel-order': {
      id: '/cancel-order'
      path: '/cancel-order'
      fullPath: '/cancel-order'
      preLoaderRoute: typeof CancelOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-sellers': {
      id: '/best-sellers'
      path: '/best-sellers'
      fullPath: '/best-sellers'
      preLoaderRoute: typeof BestSellersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  BestSellersRoute: BestSellersRoute,
  CancelOrderRoute: CancelOrderRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactUsRoute: ContactUsRoute,
  FavoritesRoute: FavoritesRoute,
  LatestOffersRoute: LatestOffersRoute,
  NewProductsRoute: NewProductsRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  OrdersRoute: OrdersRoute,
  PaymentRoute: PaymentRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrackRoute: TrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
